### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by huijuechen** [UBC-MDS/Crime_population#9]
I have uploaded a clean_data.R and the cleaned data csv, also put down the code for the first panel. 
I merged our code together, so I may changed one or two column names as it is importing data from the clean_data.csv.
It has been tested on my end and worked, please double check on your end to make sure~ thanks~

Also, for milestone 2, would you mind doing one of the following before the deadline, i will do the other one, please let me know which one you pick:

- [ ] write the write-up part

- [ ] add more than one city/crime type to the curve in panel 2 as we discussed before

Going forward, I think we should improve on:

- [ ] add colour scheme to our graphs, right now its all gray

- [ ] clean the data to be better, such as clean up city names, remove some of the regions that kind of duplicate.

Please feel free to add to the list!!!

**Comment by K3ra-y** [comment]
- [ ]  Add hover to see information of the line-plot.

**Comment by huijuechen** [comment]
- [ ] Separate tabs of first panel and second panel
- [ ] Update the axis of year for second panel starting from 1980 since data has been updated.

**Comment by huijuechen** [comment]
I have done below. I made a mistake by merging my own pull request. Please let me know if you find any issues running it.
- Separate tabs of first panel and second panel
- Clean the data to be better, such as clean up city names, remove some of the regions that kind of duplicate
- Fixed all the issues in TA's feedback except for the write-up part 


Also below for the first panel, please do the same for second panel as well, thank you!
- - [ ]  Add hover to see information of the line-plot.

For second panel, as we discussed earlier: 
- [ ] please add data points to the line, and make hover on activated on the points

Regarding Hailey/Tony's suggestions on the average line, I think it is rather the average for all cities in the states for the selected year as a base line, not the average for the selected cities(which would not be very helpful, users can pretty much eyeballing that information).
- [ ] please kindly remove the current line or update it to the average of all cities.

- [ ] For write-up this week, just a reminder, they want us to mention the change from last week's first draft to this week's second release. "Reflection on how your project has changed since Milestone 2, and why." I forgot about this part last week when writing it....
